version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: twitter_clone_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: twitter_clone_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/twitter_clone?authSource=admin
    depends_on:
      - mongodb